# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'
  targetRuntime: 'win-x64'

steps:
- script: dotnet build --configuration $(buildConfiguration) --framework $(dotNetFramework)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'andreandrade_internal(1)(29eb732c-7f74-4314-82af-336bfd45139d)'
    appType: 'webApp'
    appName: 'WebAppInsightsAA'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'

