# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# disabling the push trigger
#trigger:
#- master

variables:
  dotNetFramework: 'net6.0'
  app_service_name: 'WebAppInsightsAA'

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: 'dotnet build'
  inputs:
    version: 6.0.101

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    arguments: '--framework $(dotNetFramework)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: $(app_service_name)'
  inputs:
    azureSubscription: 'andreandrade_internal(29eb732c-7f74-4314-82af-336bfd45139d)'
    WebAppName: '$(app_service_name)'

